### ISSUE TITLE
Possible duplicate cache block in lock lab

### ISSUE THREAD

**Issue by chace20** [skyzh/6.S081-xv6-riscv-fall19#10]
https://github.com/skyzh/6.S081-xv6-riscv-fall19/blob/8df74263fdc6f143f85c6f8aaf9c7d0f42c1dfea/kernel/bio.c#L84

Hi, I think this line will violates invariant: **at most one copy of a block is cached**. 

So, the code can not ensure `Searching in the hash table for a buffer and allocating an entry for that buffer when the buffer is not found must be atomic`.

Consider a case, process **p1** and process **p2** both access block **b1**, but b1 is not in buffer list now. Then p1 execute the code `release(&bcache.lock[h])`, now p2 can search the hashtable because p1 release the `bcache.lock[h]`, but p2 will not find buffer as well as p1. Next, both p1 and p2 will recycle a buffer caching b1. But it should be at most one copy of a block is cached.

---
Why should at most one copy of a block is cached?
`It is important that there is at most one cached buffer per disk sector, to ensure that readers see writes, and because the ﬁle system uses locks on buffers for synchronization. `

---
😺

**Comment by skyzh** [comment]
Thanks for your comment! It has been so long time that I forgot about what I've written. I'm reading though my code :(

**Comment by skyzh** [comment]
You're right! Here I have two ideas to fix this.

1. a global lock for `bget`.
2. use something like reader-writer lock.

**Comment by skyzh** [comment]
I've fixed this in latest lock branch. Assume we steal a block from hashtable `_h` to `h` Now I ensure that:

1. during the process of finding a block to steal, lock to `h` is always held
2. in this way, no other process will be able to allocate buffer on `h`

I doubt that there would be deadlock if A is stealing from B and B is stealing from A concurrently. But when running tests, it seems all OK. Would you please take a look?

https://github.com/skyzh/6.S081-xv6-riscv-fall19/blob/lock/kernel/bio.c#L84

**Comment by chace20** [comment]
`A is stealing from B and B is stealing from A` may cause deadlock.

My solution is hold a big `bcache.lock` for `bcache.buf[]` when recycle an unused buffer. 
The benefit of hold a big `bcache.lock` is it can maintain global LRU, while bucket double-linked list can only get local(i.e. in this bucket) LRU. The drawback is reduce parallelism. 

Still some tradeoff in this lab.

**Comment by skyzh** [comment]
Thanks for your suggestion! It seems that we can never avoid this kind of global lock. As this issue has been well-discussed, I'll close this for now 😊

**Comment by chace20** [comment]
Yeah, there are another tricky case may cause deadlock: the new block might hash to the same bucket as the old block. 😆
