### ISSUE TITLE
Why not check bucket itself first in lock lab?

### ISSUE THREAD

**Issue by abbott-xie** [skyzh/6.S081-xv6-riscv-fall19#11]
在bget的时候，如果在一个桶中没有找到被cached的buffer，为什么直接从其他桶里开始拿，而不是先检查自己桶里有没有空余的buffer然后从自己桶里设置呢？

**Comment by skyzh** [comment]
Fixed in https://github.com/skyzh/6.S081-xv6-riscv-fall19/commit/9fc17f62722a1c531e816befb4c634457e3598cc
